namespace Barbados.StorageEngine.Exceptions
{
	public enum BarbadosExceptionCode
	{
		DatabaseDoesNotExist = 1,
		InvalidDatabaseState,
		DatabaseVersionMismatch,
		WalDoesNotExist,
		WalVersionMismatch,
		DbMagicWalMagicMismatch,
		UnexpectedEndOfFile,
		ChecksumVerificationFailed,
		MaxFileLengthReached,
		MaxPageCountReached,
		MaxTransactionCountReached,
		MaxWalCommitNumberReached,
		MaxDocumentCountReached,
		DocumentNotFound,
		CollectionDoesNotExist,
		CollectionAlreadyExists,
		IndexDoesNotExist,
		IndexAlreadyExists,
		LockDoesNotExist,
		LockNoLongerExists,
		CursorClosed,
		CursorConsumed,
		NestedTransactionDetected,
		TransactionDoesNotExist,
		TransactionUpgradeAttempt,
		TransactionScopeMismatch,
		TransactionScopeCompleted,
		TransactionTargetMismatch,
		InternalError = 0x7FFFFFFF,
	}
}
