name: 'ci'
on:
  push:
    branches: [ 'main', 'dev' ]
  workflow_call:

jobs:
  test:
    name: 'test'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'checkout'
      uses: 'actions/checkout@v4'

    - name: 'setup-dotnet'
      uses: 'actions/setup-dotnet@v4'
      with:
        dotnet-version: '9.0.x'

    - name: 'restore'
      run: 'dotnet restore'

    - name: 'build'
      run: 'dotnet build --no-restore'

    - name: 'test'
      run: 'dotnet test --no-build'
