name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    uses: ./.github/workflows/run-test.yml
    
  publish:
    name: Publish to NuGet
    needs: [test]
    runs-on: ubuntu-latest
    steps:       
    - name: Get version from release tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack -c Release --output nupkgs --no-restore --no-build /p:Version=${VERSION}
    - name: Publish
      run: | 
        dotnet nuget push nupkgs/Memonia.Barbados.QueryEngine.${VERSION}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push nupkgs/Memonia.Barbados.StorageEngine.${VERSION}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
