name: run tests
on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:
    
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test-fast:
    name: 'Fast tests'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: 'Test: Barbados.StorageEngine'
      run: dotnet test ./test/Barbados.StorageEngine.Tests --verbosity normal
      
  test-slow:
    name: 'Slow tests'
    needs: test-fast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: 'Test: Barbados.StorageEngine'
      run: dotnet test ./test/Barbados.StorageEngine.Tests.Integration --verbosity normal
